name: Auto request review


on:
  pull_request_target:
    types: [opened, synchronize, ready_for_review, reopened]


concurrency:
  group: request-review-${{ github.event.pull_request.number }}
  cancel-in-progress: true


jobs:
  auto-request-review:
    # Do not spam reviewer with PRs in forks. If fork owners wish to alert
    # people of their changes they may change this line themselves.
    if: github.repository == 'Procyonae/Cataclysm-DDA'
    name: Auto request review
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: Procyonae/auto-request-review@b32824f26643e2e3e01ef0823b034e1b91cc1ebd
        with:
          token: ${{ secrets.REVIEW_TOKEN }}
          config: .github/reviewers.yml
